services:
  ddpm-container:
    build: .
    image: ddpm-project
    container_name: ddpm-container
    stdin_open: true 
    tty: true
    volumes:
      - ./data:/app/datasets
    command: ["python", "src/main.py"]
