version: "3"
services:
  ddpm-container:
    build: .
    image: ddpm-project
    container_name: ddpm-container
    stdin_open: true # Keeps stdin open
    tty: true # Allocates a pseudo-TTY
    volumes:
      - ./kaggle.json:/root/.kaggle/kaggle.json
