services:
  ddpm-container:
    build: .
    image: ddpm-project
    container_name: ddpm-container
    stdin_open: true 
    tty: true
    volumes:
      - ./data:/app/datasets
      - ./images/celeba:/app/images/celeba
      - ./images/flowers:/app/images/flowers
    command: ["python", "src/main.py"]
